mysql

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -21,29 +21,29 @@ empty:
   script:
     - echo "empty"
 
-# lint:
-#  image: $CI_REGISTRY/mattermost/ci/images/golangci-lint:v1.33.2-1
-#  stage: .pre
-#  script:
-#    - GO111MODULE=off GOBIN=$PWD/bin go get -u github.com/mattermost/mattermost-govet
-#    - make config-reset
-#    - make check-style #todo MM_VET_OPENSPEC_PATH='$CI_PROJECT_DIR/mattermost-api-reference/v4/html/static/mattermost-openapi-v4.yaml'
-#  timeout: 60 mins
-#  rules:
-#    - if: '$TEST == "yes"'
+lint:
+ image: $CI_REGISTRY/mattermost/ci/images/golangci-lint:v1.33.2-1
+ stage: .pre
+ script:
+   - GO111MODULE=off GOBIN=$PWD/bin go get -u github.com/mattermost/mattermost-govet
+   - make config-reset
+   - make check-style #todo MM_VET_OPENSPEC_PATH='$CI_PROJECT_DIR/mattermost-api-reference/v4/html/static/mattermost-openapi-v4.yaml'
+ timeout: 60 mins
+ rules:
+   - if: '$TEST == "yes"'
 
-# layers:
-#  image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-server:20201119_golang-1.15.5
-#  stage: .pre
-#  script:
-#    - make store-layers
-#    - if [[ -n $(git status --porcelain) ]]; then echo "Please update the store layers using make store-layers"; exit 1; fi
-#    - git reset --hard
-#    - make app-layers
-#    - if [[ -n $(git status --porcelain) ]]; then echo "Please update the app layers using make app-layers"; exit 1; fi
-#    - git reset --hard
-#  rules:
-#    - if: '$TEST == "yes"'
+layers:
+ image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-server:20201119_golang-1.15.5
+ stage: .pre
+ script:
+   - make store-layers
+   - if [[ -n $(git status --porcelain) ]]; then echo "Please update the store layers using make store-layers"; exit 1; fi
+   - git reset --hard
+   - make app-layers
+   - if [[ -n $(git status --porcelain) ]]; then echo "Please update the app layers using make app-layers"; exit 1; fi
+   - git reset --hard
+ rules:
+   - if: '$TEST == "yes"'
 
 #test-postgres:
 #  extends: .test
@@ -67,8 +67,6 @@ empty:
 
 test-schema-postgres:
  extends: .test-schema
-#  tags:
-#    - docker
  script:
     - |
       echo "Creating databases"
@@ -77,11 +75,11 @@ test-schema-postgres:
       kubectl exec -n mm-ci -t $(get_pod_name "postgres") -- psql -U mmuser -d migrated < ./scripts/mattermost-postgresql-5.0.sql
 
     - |
-      echo "Copying files to build-server"
-      kubectl cp -n mm-ci $CI_PROJECT_DIR $(get_pod_name "build-server"):/build
+      echo "Copying files to build-server-postgres"
+      kubectl cp -n mm-ci $CI_PROJECT_DIR $(get_pod_name "build-server-postgres"):/build
       echo "TODO"
-      kubectl exec -n mm-ci -t $(get_pod_name "build-server") -- bash -c "cd /build/mattermost-server; MM_SQLSETTINGS_DATASOURCE='postgres://mmuser:mostest@ci-${CI_PIPELINE_ID}-postgres:5432/latest?sslmode=disable&connect_timeout=10' MM_SQLSETTINGS_DRIVERNAME='postgres' go run ./cmd/mattermost/main.go version"
-      kubectl logs -n mm-ci $(get_pod_name "build-server")
+      kubectl exec -n mm-ci -t $(get_pod_name "build-server-postgres") -- bash -c "cd /build/mattermost-server; MM_SQLSETTINGS_DATASOURCE='postgres://mmuser:mostest@ci-${CI_PIPELINE_ID}-postgres:5432/latest?sslmode=disable&connect_timeout=10' MM_SQLSETTINGS_DRIVERNAME='postgres' go run ./cmd/mattermost/main.go version"
+      kubectl logs -n mm-ci $(get_pod_name "build-server-postgres")
 
     - |
       echo "Generating dump"
@@ -94,33 +92,32 @@ test-schema-postgres:
  rules:
    - if: '$TEST == "yes"'
 
-# test-schema-mysql:
-#  extends: .test-schema
-# #  tags:
-# #    - docker
-#  script:
-#    - echo "Creating databases"
-#    - docker-compose --no-ansi exec -T mysql mysql -uroot -pmostest -e "CREATE DATABASE migrated; CREATE DATABASE latest; GRANT ALL PRIVILEGES ON migrated.* TO mmuser; GRANT ALL PRIVILEGES ON latest.* TO mmuser"
-#    - echo "Importing mysql dump from version 5.0"
-#    - docker-compose --no-ansi exec -T mysql mysql -D migrated -uroot -pmostest < ../scripts/mattermost-mysql-5.0.sql
-#    - >
-#      docker run -d -it --name server-mysql --net build_mm-test \
-#        --env-file="dotenv/test-schema-validation.env" \
-#        --env MM_SQLSETTINGS_DATASOURCE="mmuser:mostest@tcp(mysql:3306)/migrated?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s" \
-#        --env MM_SQLSETTINGS_DRIVERNAME=mysql \
-#        -v $CI_PROJECT_DIR:/mattermost-server \
-#        -w /mattermost-server \
-#        mattermost/mattermost-build-server:20201119_golang-1.15.5 \
-#        bash -c "ulimit -n 8096; make ARGS='version' run-cli && make MM_SQLSETTINGS_DATASOURCE='mmuser:mostest@tcp(mysql:3306)/latest?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s' ARGS='version' run-cli"
-#    - docker logs -f server-mysql
-#    - echo "Ignoring known MySQL mismatch 'ChannelMembers.SchemeGuest'"
-#    - docker-compose --no-ansi exec -T mysql mysql -D migrated -uroot -pmostest -e "ALTER TABLE ChannelMembers DROP COLUMN SchemeGuest;" || echo "drop failed"
-#    - docker-compose --no-ansi exec -T mysql mysql -D latest -uroot -pmostest -e "ALTER TABLE ChannelMembers DROP COLUMN SchemeGuest;" || echo "drop failed"
-#    - echo "Generating dump"
-#    - docker-compose --no-ansi exec -T mysql mysqldump --skip-opt --no-data --compact -u root -pmostest migrated > migrated.sql
-#    - docker-compose --no-ansi exec -T mysql mysqldump --skip-opt --no-data --compact -u root -pmostest latest > latest.sql
-#    - echo "Removing databases created for db comparison"
-#    - docker-compose --no-ansi exec -T mysql mysql -uroot -pmostest -e 'DROP DATABASE migrated; DROP DATABASE latest'
-#    - echo "Generating diff"
-#  rules:
-#    - if: '$TEST == "yes"'
+test-schema-mysql:
+  extends: .test-schema
+  script:
+    - |
+      echo "Creating databases"
+      kubectl exec -n mm-ci -t $(get_pod_name "mysql") -- mysql -uroot -pmostest -e "CREATE DATABASE migrated; CREATE DATABASE latest; GRANT ALL PRIVILEGES ON migrated.* TO mmuser; GRANT ALL PRIVILEGES ON latest.* TO mmuser"
+      echo "Importing mysql dump from version 5.0"
+      kubectl exec -n mm-ci -t $(get_pod_name "mysql") -- mysql -D migrated -uroot -pmostest < ../scripts/mattermost-mysql-5.0.sql
+
+    - |
+      echo "Copying files to build-server-mysql"
+      kubectl cp -n mm-ci $CI_PROJECT_DIR $(get_pod_name "build-server-mysql"):/build
+      echo "TODO"
+      kubectl exec -n mm-ci -t $(get_pod_name "build-server-mysql") -- bash -c "cd /build/mattermost-server; MM_SQLSETTINGS_DATASOURCE='mmuser:mostest@tcp(ci-${CI_PIPELINE_ID}-mysql:3306)/latest?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s' MM_SQLSETTINGS_DRIVERNAME='mysql' go run ./cmd/mattermost/main.go version"
+      kubectl logs -n mm-ci $(get_pod_name "build-server-mysql")
+
+    - |
+      echo "Ignoring known MySQL mismatch 'ChannelMembers.SchemeGuest'"
+      kubectl exec -n mm-ci -t $(get_pod_name "mysql") -- mysql -D migrated -uroot -pmostest -e "ALTER TABLE ChannelMembers DROP COLUMN SchemeGuest;" || echo "drop failed"
+      kubectl exec -n mm-ci -t $(get_pod_name "mysql") -- mysql -D latest -uroot -pmostest -e "ALTER TABLE ChannelMembers DROP COLUMN SchemeGuest;" || echo "drop failed"
+      echo "Generating dump"
+      kubectl exec -n mm-ci -t $(get_pod_name "mysql") -- mysqldump --skip-opt --no-data --compact -u root -pmostest migrated > migrated.sql
+      kubectl exec -n mm-ci -t $(get_pod_name "mysql") -- mysqldump --skip-opt --no-data --compact -u root -pmostest latest > latest.sql
+      echo "Removing databases created for db comparison"
+      kubectl exec -n mm-ci -t $(get_pod_name "mysql") -- mysql -uroot -pmostest -e 'DROP DATABASE migrated; DROP DATABASE latest'
+      echo "Generating diff"
+      diff migrated.sql latest.sql > diff.txt && echo "Both schemas are same" || (echo "Schema mismatch" && cat diff.txt && exit 1)
+  rules:
+    - if: '$TEST == "yes"'
