Automated cherry pick of #12560 (#12706)
* MM-19050 Testing circle ci fix

* MM-19050 Testing circle ci fix

* MM-19050 Fixing the missing redux error

* MM-19050 Removing webapp testing

* MM-19050 Movinng npm ci

* MM-19050 Readding test step

* MM-19050 Readding test step

* Removing curl step

* Removing curl step

* Adding logic for curl fails

* MM-19050 Testing e2e functionality

* MM-19050 Testing e2e functionality

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,7 +27,11 @@ jobs:
           git checkout $CIRCLE_BRANCH || git checkout master
           export WEBAPP_GIT_COMMIT=$(git rev-parse HEAD)
           echo "$WEBAPP_GIT_COMMIT"
-          curl -f -o ./dist.tar.gz https://releases.mattermost.com/mattermost-webapp/commit/${WEBAPP_GIT_COMMIT}/mattermost-webapp.tar.gz && mkdir ./dist && tar -xvf ./dist.tar.gz -C ./dist --strip-components=1 || make node_modules test build
+          curl -f -o ./dist.tar.gz https://releases.mattermost.com/mattermost-webapp/commit/${WEBAPP_GIT_COMMIT}/mattermost-webapp.tar.gz && mkdir ./dist && tar -xvf ./dist.tar.gz -C ./dist --strip-components=1 || echo "curl failed" && export CURL_FAILED=1
+          if [ $CURL_FAILED -eq 1 ]
+          then
+            npm ci && cd node_modules/mattermost-redux && npm install && npm run build && cd ../.. && make build
+          fi
       - persist_to_workspace:
           root: /go/src/github.com/mattermost
           paths:
