Comment check-deps.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -38,55 +38,55 @@ jobs:
             - mattermost-webapp
             - mattermost-server
 
-  check-deps:
-    parameters:
-      cve_data_directory:
-        type: string
-        default: "~/.owasp/dependency-check-data"
-    working_directory: ~/mattermost/mattermost-server
-    executor: owasp/default
-    environment:
-      version_url: "https://jeremylong.github.io/DependencyCheck/current.txt"
-      executable_url: "https://dl.bintray.com/jeremy-long/owasp/dependency-check-VERSION-release.zip"
-    steps:
-      - attach_workspace:
-          at: ~/mattermost/
-      - run:
-          name: Checkout config
-          command: cd .. && git clone --depth=1 https://github.com/mattermost/security-automation-config
-      - run:
-          name: Install Go
-          command: sudo apt-get update && sudo apt-get install golang
-      - owasp/with_commandline:
-          steps:
-            # Taken from https://github.com/entur/owasp-orb/blob/master/src/%40orb.yml#L349-L361
-            - owasp/generate_cache_keys:
-                cache_key: commmandline-default-cache-key-v7
-            - owasp/restore_owasp_cache
-            - run:
-                name: Update OWASP Dependency-Check Database
-                command: |
-                  if ! ~/.owasp/dependency-check/bin/dependency-check.sh --data << parameters.cve_data_directory >> --updateonly; then
-                    # Update failed, probably due to a bad DB version; delete cached DB and try again
-                    rm -rv ~/.owasp/dependency-check-data/*.db
-                    ~/.owasp/dependency-check/bin/dependency-check.sh --data << parameters.cve_data_directory >> --updateonly
-                  fi
-            - owasp/store_owasp_cache:
-                cve_data_directory: <<parameters.cve_data_directory>>
-            - run:
-                name: Run OWASP Dependency-Check Analyzer
-                command: |
-                  ~/.owasp/dependency-check/bin/dependency-check.sh \
-                    --data << parameters.cve_data_directory >> --format ALL --noupdate --enableExperimental \
-                    --propertyfile ../security-automation-config/dependency-check/dependencycheck.properties \
-                    --suppression ../security-automation-config/dependency-check/suppression.xml \
-                    --suppression ../security-automation-config/dependency-check/suppression.$CIRCLE_PROJECT_REPONAME.xml \
-                    --scan './**/*' || true
-            - owasp/collect_reports:
-                persist_to_workspace: false
-      - run:
-          name: Post results to Mattermost
-          command: go run ../security-automation-config/dependency-check/post_results.go
+#  check-deps:
+#    parameters:
+#      cve_data_directory:
+#        type: string
+#        default: "~/.owasp/dependency-check-data"
+#    working_directory: ~/mattermost/mattermost-server
+#    executor: owasp/default
+#    environment:
+#      version_url: "https://jeremylong.github.io/DependencyCheck/current.txt"
+#      executable_url: "https://dl.bintray.com/jeremy-long/owasp/dependency-check-VERSION-release.zip"
+#    steps:
+#      - attach_workspace:
+#          at: ~/mattermost/
+#      - run:
+#          name: Checkout config
+#          command: cd .. && git clone --depth=1 https://github.com/mattermost/security-automation-config
+#      - run:
+#          name: Install Go
+#          command: sudo apt-get update && sudo apt-get install golang
+#      - owasp/with_commandline:
+#          steps:
+#            # Taken from https://github.com/entur/owasp-orb/blob/master/src/%40orb.yml#L349-L361
+#            - owasp/generate_cache_keys:
+#                cache_key: commmandline-default-cache-key-v7
+#            - owasp/restore_owasp_cache
+#            - run:
+#                name: Update OWASP Dependency-Check Database
+#                command: |
+#                  if ! ~/.owasp/dependency-check/bin/dependency-check.sh --data << parameters.cve_data_directory >> --updateonly; then
+#                    # Update failed, probably due to a bad DB version; delete cached DB and try again
+#                    rm -rv ~/.owasp/dependency-check-data/*.db
+#                    ~/.owasp/dependency-check/bin/dependency-check.sh --data << parameters.cve_data_directory >> --updateonly
+#                  fi
+#            - owasp/store_owasp_cache:
+#                cve_data_directory: <<parameters.cve_data_directory>>
+#            - run:
+#                name: Run OWASP Dependency-Check Analyzer
+#                command: |
+#                  ~/.owasp/dependency-check/bin/dependency-check.sh \
+#                    --data << parameters.cve_data_directory >> --format ALL --noupdate --enableExperimental \
+#                    --propertyfile ../security-automation-config/dependency-check/dependencycheck.properties \
+#                    --suppression ../security-automation-config/dependency-check/suppression.xml \
+#                    --suppression ../security-automation-config/dependency-check/suppression.$CIRCLE_PROJECT_REPONAME.xml \
+#                    --scan './**/*' || true
+#            - owasp/collect_reports:
+#                persist_to_workspace: false
+#      - run:
+#          name: Post results to Mattermost
+#          command: go run ../security-automation-config/dependency-check/post_results.go
 
   # TODO: enable this step when the i18n-extract works with mattermost-server only
   # and not depend on both mm-server/enterprise
@@ -453,10 +453,10 @@ workflows:
                 - master
                 - /^release-.*/
                 - cloud
-      - check-deps:
-          context: sast-webhook
-          requires:
-            - setup
+#      - check-deps:
+#          context: sast-webhook
+#          requires:
+#            - setup
       # - check-i18n:
       #     requires:
       #       - setup
