[skip ci] Improve rolling upgrade E2E tests

diff --git a/.github/workflows/e2e-tests-ci-template.yml b/.github/workflows/e2e-tests-ci-template.yml
--- a/.github/workflows/e2e-tests-ci-template.yml
+++ b/.github/workflows/e2e-tests-ci-template.yml
@@ -37,9 +37,6 @@ on:
       SERVER_IMAGE:
         type: string
         required: false
-      SERVER_IMAGE_UPGRADEFROM:
-        type: string # If this is set, perform a rolling-upgrade test starting from this server image
-        required: false
       ENABLED_DOCKER_SERVICES:
         type: string
         required: false
@@ -56,6 +53,12 @@ on:
         type: string
         required: false
       REPORT_TYPE:
+        type: string
+        required: false
+      ROLLINGRELEASE_commit_sha: # Unused for now, can be useful for implementing https://mattermost.atlassian.net/browse/CLD-7983
+        type: string
+        required: false
+      ROLLINGRELEASE_SERVER_IMAGE:
         type: string
         required: false
     secrets:
@@ -256,7 +259,6 @@ jobs:
       AUTOMATION_DASHBOARD_TOKEN: "${{ secrets.AUTOMATION_DASHBOARD_TOKEN }}"
       SERVER: "${{ inputs.SERVER }}"
       SERVER_IMAGE: "${{ inputs.SERVER_IMAGE }}"
-      SERVER_IMAGE_UPGRADEFROM: "${{ inputs.SERVER_IMAGE_UPGRADEFROM }}"
       MM_LICENSE: "${{ secrets.MM_LICENSE }}"
       ENABLED_DOCKER_SERVICES: "${{ inputs.ENABLED_DOCKER_SERVICES }}"
       TEST_FILTER: "${{ inputs.TEST_FILTER }}"
@@ -267,6 +269,7 @@ jobs:
       CYPRESS_pushNotificationServer: "${{ secrets.PUSH_NOTIFICATION_SERVER }}"
       CWS_URL: "${{ secrets.CWS_URL }}"
       CWS_EXTRA_HTTP_HEADERS: "${{ secrets.CWS_EXTRA_HTTP_HEADERS }}"
+      ROLLINGRELEASE_SERVER_IMAGE: "${{ inputs.ROLLINGRELEASE_SERVER_IMAGE }}"
     steps:
       - name: ci/checkout-repo
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
@@ -290,36 +293,25 @@ jobs:
           cache: npm
           cache-dependency-path: "e2e-tests/cypress/package-lock.json"
       - name: ci/e2e-test
-        if: "inputs.SERVER_IMAGE_UPGRADEFROM == ''"
         run: |
-          make
-      - name: ci/e2e-test-rolling-release
-        if: "inputs.SERVER_IMAGE_UPGRADEFROM != ''"
-        run: |
-          set -eu -o pipefail
-          # Run the individual steps from 'make run', to make checks and switch the server image midway and keep a single cloud user
-          echo "RollingRelease: initializing cloud user"
           make cloud-init
-          # Run initial smoketests in a subshell, to isolate the environment
-          echo "RollingRelease: running initial smoketest against image $SERVER_IMAGE_UPGRADEFROM"
-          (
-          export SERVER_IMAGE="$SERVER_IMAGE_UPGRADEFROM"
-          export TEST_FILTER=""
-          export AUTOMATION_DASHBOARD_URL=""
-          make start-server && make prepare-server && make run-test
-          )
-          # Assert that the smokests results are successful
-          echo "RollingRelease: asserting smoketest result has zero failures."
-          FAILURES=$(find cypress/results -name '*.json' | xargs -l jq -r '.stats.failures' | jq -s add)
-          if [ "$FAILURES" -ne "0" ]; then
-            echo "RollingRelease: initial smoketest for rolling release E2E run has nonzero ($FAILURES) failures. Aborting test run." >&2
-            exit 1
+          if [ -n "$ROLLINGRELEASE_SERVER_IMAGE" ]; then
+            (
+            echo "RollingRelease: running initial smoketest against image $ROLLINGRELEASE_SERVER_IMAGE"
+            export SERVER_IMAGE="$ROLLINGRELEASE_SERVER_IMAGE"
+            export TEST_FILTER=""
+            export AUTOMATION_DASHBOARD_URL=""
+            make
+            )
+            echo "RollingRelease: asserting smoketest result has zero failures."
+            FAILURES=$(find cypress/results -name '*.json' | xargs -l jq -r '.stats.failures' | jq -s add)
+            if [ "$FAILURES" -ne "0" ]; then
+              echo "RollingRelease: initial smoketest for rolling release E2E run has nonzero ($FAILURES) failures. Aborting test run." >&2
+              exit 1
+            fi
+            rm -rfv cypress/results
           fi
-          rm -rfv cypress/results
-          # Run actual tests against the new image
-          echo "RollingRelease: running full E2E test against image $SERVER_IMAGE"
-          make start-server && make prepare-server && make run-test
-          echo "RollingRelease: tearing down cloud user"
+          make
           make cloud-teardown
       - name: ci/e2e-test-store-results
         uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
